# Generated by Django 4.0.6 on 2022-12-26 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=100)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteApp.organizations')),
            ],
        ),
        migrations.AddField(
            model_name='organizations',
            name='members',
            field=models.ManyToManyField(blank=True, to='voteApp.voters'),
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=30)),
                ('vote_count', models.IntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteApp.organizations')),
                ('supporters', models.ManyToManyField(blank=True, to='voteApp.voters')),
            ],
        ),
    ]
