# Generated by Django 4.0.6 on 2022-12-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
