# Generated by Django 4.0.6 on 2022-12-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0005_remove_voters_firstname_remove_voters_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='LastName',
        ),
        migrations.AddField(
            model_name='contestant',
            name='FullName',
            field=models.CharField(default='Contester', max_length=150),
        ),
        migrations.AlterField(
            model_name='voters',
            name='FullName',
            field=models.CharField(default='User', max_length=150, unique=True),
        ),
    ]
