# Generated by Django 4.0.6 on 2022-12-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0006_remove_contestant_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='FullName',
            field=models.CharField(default='Contester', max_length=150, unique=True),
        ),
    ]
