# Generated by Django 4.0.6 on 2022-12-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0007_alter_contestant_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='identity',
            field=models.BigIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
