# Generated by Django 4.0.6 on 2022-12-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0008_organizations_identity_alter_organizations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='FullName',
            field=models.CharField(default='Contester', max_length=150),
        ),
    ]
