# Generated by Django 4.0.6 on 2022-12-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0010_alter_voters_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='voters',
            name='identity',
            field=models.BigIntegerField(default=0),
        ),
    ]
