# Generated by Django 4.0.6 on 2022-12-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0011_alter_voters_email_alter_voters_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
