# Generated by Django 4.0.6 on 2022-12-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0012_alter_organizations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='identity',
            field=models.BigIntegerField(default=0),
        ),
    ]
