# Generated by Django 4.0.6 on 2022-12-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0013_alter_organizations_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='supporters',
        ),
    ]
