# Generated by Django 4.0.6 on 2022-12-30 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0016_contestant_validate_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voteApp.organizations'),
        ),
    ]
